services:
  app:
    image: gucheen/actual-budget-bot:nightly
    environment:
      NODE_ENV: production
    volumes:
      - .env:/home/node/app/.env
      - ./src/mapping.json:/home/node/app/src/mapping.json
      - ./actual-data:/home/node/app/actual-data
      - ./uploads:/home/node/app/uploads
    ports:
      - 8000:8000
  cnocr:
    image: breezedeus/cnocr:latest
    environment:
      HF_ENDPOINT: https://hf-mirror.com
    command: bash -c "pip install -U cnocr cnstd --index-url https://mirrors.aliyun.com/pypi/simple && cnocr serve -H 0.0.0.0 -p 8501"
